x=int(input("Enter how many ""Introduction To Python Programming"" Books are required:"))
y=int(input("Enter how many ""Python Library CookBook"" book are required:"))
z=int(input("Enter how many ""Data Science In Python"" books are required:"))
total_cost = (x*499.00)+(y*855.00)+(z*645.00)
include_taxes = (total_cost*0.12)
including_deliver_charge=(total_cost+ include_taxes+250.00)
print("total invoice amount for the purchase made:",including_deliver_charge)